apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-portfolio-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-portfolio
  template:
    metadata:
      labels:
        app: devops-portfolio
    spec:
      containers:
      - name: devops-portfolio-container
        image: singhkpritam/devops-portfolio:v1
        imagePullPolicy: Always   # 🔥 ADD THIS
        ports:
        - containerPort: 80